import type { Accommodation, Category } from "@/types";

export const CATEGORIES: Category[] = [
  { id: "all", label: "Todo", icon: "🌍" },
  { id: "beach", label: "Playa", icon: "🏖️" },
  { id: "mansion", label: "Mansiones", icon: "🏰" },
  { id: "city", label: "Ciudad", icon: "🏙️" },
  { id: "countryside", label: "Campo", icon: "🌲" },
  { id: "design", label: "Diseño", icon: "🎨" },
];

export const ACCOMMODATIONS: Accommodation[] = [
  {
    id: "ba-1",
    title: "Apartamento en Buenos Aires",
    city: "Buenos Aires",
    country: "Argentina",
    description: "Apartamento moderno cerca de Palermo Soho.",
    pricePerNight: 88,
    rating: 4.92,
    reviewCount: 145,
    category: "city",
    imageLabel: "Sala y habitación luminosa",
    coordinates: { lat: -34.6037, lng: -58.3816 },
    amenities: ["WiFi", "Cocina", "Aire acondicionado", "Lavadora"],
    host: { name: "Lucía", yearsHosting: 6, avatarLabel: "Avatar de Lucía" },
    photos: ["Living con ventanal", "Dormitorio principal", "Balcón", "Cocina"],
  },
  {
    id: "ba-2",
    title: "Loft en Recoleta",
    city: "Buenos Aires",
    country: "Argentina",
    description: "Loft amplio con diseño contemporáneo.",
    pricePerNight: 96,
    rating: 4.86,
    reviewCount: 98,
    category: "design",
    imageLabel: "Loft con decoración minimalista",
    coordinates: { lat: -34.588, lng: -58.396 },
    amenities: ["WiFi", "Calefacción", "Ascensor", "Cocina"],
    host: { name: "Tomás", yearsHosting: 4, avatarLabel: "Avatar de Tomás" },
    photos: ["Área social", "Dormitorio", "Comedor", "Vista urbana"],
  },
  {
    id: "md-1",
    title: "Hotel 1881 Madrid Ventas",
    city: "Madrid",
    country: "España",
    description: "Habitación privada en hotel boutique céntrico.",
    pricePerNight: 121,
    rating: 4.8,
    reviewCount: 233,
    category: "city",
    imageLabel: "Fachada del hotel en Madrid",
    coordinates: { lat: 40.4168, lng: -3.7038 },
    amenities: ["Desayuno", "Recepción 24h", "WiFi", "Ascensor"],
    host: { name: "Carmen", yearsHosting: 9, avatarLabel: "Avatar de Carmen" },
    photos: ["Recepción", "Habitación doble", "Comedor", "Exterior"],
  },
  {
    id: "md-2",
    title: "NH Madrid Chamberí",
    city: "Madrid",
    country: "España",
    description: "Alojamiento elegante en zona gastronómica.",
    pricePerNight: 138,
    rating: 4.88,
    reviewCount: 201,
    category: "mansion",
    imageLabel: "Hotel con iluminación nocturna",
    coordinates: { lat: 40.4333, lng: -3.7032 },
    amenities: ["WiFi", "Gimnasio", "Parking", "Cocina"],
    host: { name: "Álvaro", yearsHosting: 7, avatarLabel: "Avatar de Álvaro" },
    photos: ["Lobby", "Habitación premium", "Terraza", "Restaurante"],
  },
  {
    id: "bi-1",
    title: "Apartamento en Bilbao",
    city: "Bilbao",
    country: "España",
    description: "Apartamento completo en Casco Viejo.",
    pricePerNight: 109,
    rating: 4.82,
    reviewCount: 189,
    category: "city",
    imageLabel: "Salón con cocina abierta",
    coordinates: { lat: 43.263, lng: -2.935 },
    amenities: ["WiFi", "Cocina", "Lavadora", "Mascotas permitidas"],
    host: { name: "Iker", yearsHosting: 5, avatarLabel: "Avatar de Iker" },
    photos: ["Salón", "Cocina", "Dormitorio", "Baño"],
  },
  {
    id: "bi-2",
    title: "Estudio junto al río",
    city: "Bilbao",
    country: "España",
    description: "Espacio acogedor con vista al paseo costero.",
    pricePerNight: 94,
    rating: 4.76,
    reviewCount: 121,
    category: "beach",
    imageLabel: "Estudio moderno con vista exterior",
    coordinates: { lat: 43.267, lng: -2.939 },
    amenities: ["WiFi", "Calefacción", "Cocina", "TV"],
    host: { name: "Nora", yearsHosting: 3, avatarLabel: "Avatar de Nora" },
    photos: ["Vista principal", "Dormitorio", "Comedor", "Vista del río"],
  },
];
